# Notice: This template has only been tested 
# under Python27 + GAE standard environment
application: sample-app
version: 1
runtime: python27
# threadsafe is required but can be either true or 
# false. For some package, it should be true e.g. Flask
threadsafe: false
api_version: 1

handlers:
- url: /
  static_files: www/Login.html
  upload: www/Login.html
  
- url: /app/.*
  script: ajaxpost.app
  
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)